### ISSUE TITLE
希望可以导出适合手机屏幕的竖屏图片，谢谢！

### ISSUE THREAD

**Issue by Egi0lg** [gantrol/Bing-Chat-Saver#1]
增加输出样式的设置选项，比如竖屏、横屏等，方便手机上共享浏览

**Comment by gantrol** [comment]
已添加至[TODO](https://github.com/users/gantrol/projects/5/views/1)

**Comment by gantrol** [comment]
已更新 https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.1.2-alpha
