### ISSUE TITLE
nice extension, but the latest version on Mar. 14 is another extension actually

### ISSUE THREAD

**Issue by potus2030** [gantrol/Bing-Chat-Saver#14]
latest version on Mar. 14 is another extension actually, please check it.

**Comment by gantrol** [comment]
Thanks for feedback, I check it now.

**Comment by gantrol** [comment]
The problem has been fixed. I mixed up the compressed files of two different plugins. Thanks again.

https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2

**Comment by potus2030** [comment]
Wow, that was fast, thank you.
