### ISSUE TITLE
提一点建议

### ISSUE THREAD

**Issue by Pa-trick** [gantrol/Bing-Chat-Saver#19]
1. 能修改一下聊天记录里的问题的字体颜色吗，看图片右边问题的时候很费眼睛
2. 可以对聊天记录中的会话增加一个删除按钮吗，这样就可以只保留想保存的会话，回顾的时候没那么多无用会话，效率比较高
<img width="1118" alt="对话" src="https://user-images.githubusercontent.com/42671505/226199435-4ea76430-c698-460a-a13e-abd95dbad9ff.png">

**Comment by Pa-trick** [comment]
用暗黑模式的人还是比较多，建议颜色调整到日间和夜间都能看清

**Comment by gantrol** [comment]
感谢反馈，删除按钮在计划中，暗黑模式这个确实没考虑到，会改

**Comment by Pa-trick** [comment]
> 暗黑模式已经调节
> 
> https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.1
> 
> ![image](https://user-images.githubusercontent.com/31330732/226614737-78df1227-57cf-49a0-8ab0-cba96deb5a9d.png)

![image](https://user-images.githubusercontent.com/42671505/226625700-3fbac386-2e5b-4f39-a29d-19e60c916bee.png)
![image](https://user-images.githubusercontent.com/42671505/226625896-482f460b-0ab7-4807-b73f-c33055de7cf4.png)
好像上传错了，我安装了最新的，气泡还是跟以前一样

**Comment by gantrol** [comment]
> 好像上传错了，我安装了最新的，气泡还是跟以前一样

确实搞错了，已经重新上传：https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.1

**Comment by Pa-trick** [comment]
> > 好像上传错了，我安装了最新的，气泡还是跟以前一样
> 
> 确实搞错了，已经重新上传：https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.1

这次对了，感谢，这个很好用，希望会话删除功能早点实现，这样就能当笔记本了！

**Comment by Pa-trick** [comment]
> > 好像上传错了，我安装了最新的，气泡还是跟以前一样
> 
> 确实搞错了，已经重新上传：https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.1

会话能自己重命名就更好了，检索起来更也更有针对性

**Comment by gantrol** [comment]
> 这次对了，感谢，这个很好用，希望会话删除功能早点实现，这样就能当笔记本了！

下一个功能应该是pdf，然后就是删除。我每天会抽一点时间做，慢慢磨吧……

还有提醒一下，数据是跟着插件一块走的，删了就没了。

**Comment by gantrol** [comment]
删除功能已加 https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.3

**Comment by gantrol** [comment]
最新版已发布到 https://chrome.google.com/webstore/detail/bing-chat-saver/ficbllnhlgldegblbimkeldcdhfjppkg?hl=zh-CN

**Comment by Pa-trick** [comment]
> 最新版已发布到 https://chrome.google.com/webstore/detail/bing-chat-saver/ficbllnhlgldegblbimkeldcdhfjppkg?hl=zh-CN

用上了，很好用！感谢！
