### ISSUE TITLE
Better naming convention for autosaved documents

### ISSUE THREAD

**Issue by Denubis** [gantrol/Bing-Chat-Saver#22]
On export, it might be worth having a naming convention of datestamp and the first words of the first message, to better clarify the different possible files.

**Comment by gantrol** [comment]
Good idea.

**Comment by gantrol** [comment]
Simply cut the first 25 character of the first question. https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.2

![image](https://user-images.githubusercontent.com/31330732/227554009-32320e7b-cd05-44e3-8a45-a6951fbd45a9.png)

**Comment by Denubis** [comment]
Looks good to me. Thanks for making this tool!
