### ISSUE TITLE
聊天记录保存不全

### ISSUE THREAD

**Issue by riverai** [gantrol/Bing-Chat-Saver#27]
现在bing的搜索的一个特点是搜索深度不像人那么好，但是看信息非常方便，特别是给出的引用来源挺值得专门看的。

不过这里的引用来源有两个问题：

1. 查看更多信息里面提到的来源多过引用的来源
2. 有时候引用的信息其实不是来自有123标注的来源，而是“更多”里面的来源。

现在保存的聊天记录，只有内容主体，也只包含了明确表明的引用来源。
于是“更多”里面的来源就丢失了，而且有的时候给出的来源可以说是牛头不对马嘴，实际上汇总的内容完全来自“更多”里面的网页。但是目前自动保存之后，这些内容也丢失了。

**Comment by gantrol** [comment]
感谢反馈。

参考有保存，没在聊天记录显示。后面会加

**Comment by gantrol** [comment]
已有引用，最新版已发布到 https://chrome.google.com/webstore/detail/bing-chat-saver/ficbllnhlgldegblbimkeldcdhfjppkg?hl=zh-CN
