### ISSUE TITLE
聊天记录删除功能

### ISSUE THREAD

**Issue by truthNihilism** [gantrol/Bing-Chat-Saver#28]
有对于自动保存的聊天记录的选中删除功能吗？感觉自动保存的聊天记录过多的时候，不太方便查找，虽然提供了搜索栏。

**Comment by gantrol** [comment]
有计划做，这个周末会尝试发布一个版本

**Comment by gantrol** [comment]
已修复，如果想等谷歌商场的版本的话，大概是后天通过审核。https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.3

**Comment by gantrol** [comment]
最新版已发布到 https://chrome.google.com/webstore/detail/bing-chat-saver/ficbllnhlgldegblbimkeldcdhfjppkg?hl=zh-CN
