### ISSUE TITLE
提个建议,开启扩展的时候没法选择更改微软提供的三个模式,希望可以修改一下

### ISSUE THREAD

**Issue by young-1-forever** [gantrol/Bing-Chat-Saver#29]

**Comment by gantrol** [comment]
这个版本就改了， https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.1
![image](https://user-images.githubusercontent.com/31330732/232264653-0a0fa6a8-e1e5-49b6-9887-967d093b6754.png)

**Comment by gantrol** [comment]
最新版已发布到 https://chrome.google.com/webstore/detail/bing-chat-saver/ficbllnhlgldegblbimkeldcdhfjppkg?hl=zh-CN
