### ISSUE TITLE
Export 按钮不见了

### ISSUE THREAD

**Issue by z14git** [gantrol/Bing-Chat-Saver#31]
貌似从昨天开始就这样了。
而且在 UI 设置中，即使勾选了 `Hide feedback button`，但依然会显示 Feedback 按钮

**Comment by gantrol** [comment]
我今天看看，昨天微软有一次大更新。 https://blogs.microsoft.com/blog/2023/05/04/announcing-the-next-wave-of-ai-innovation-with-microsoft-bing-and-edge/

**Comment by gantrol** [comment]
修复，https://github.com/gantrol/Bing-Chat-Saver/releases/tag/v0.2.4

**Comment by z14git** [comment]
感谢修复👍
