### ISSUE TITLE
突然发现不工作了

### ISSUE THREAD

**Issue by skyclearsf** [gantrol/Bing-Chat-Saver#33]
之前工作的好好的，现在Edge dev 114下，bing chat页面上没有了导出和预览按钮了，插件好象不工作。
检查了与其他插件，没有冲突，广告拦截类插件也关闭了。还是不工作。
大家有这个问题吗？

**Comment by skyclearsf** [comment]
升级以后好了！

**Comment by gantrol** [comment]
这个已修复，5 月 4 号的更新影响到了。release 发布了，chrome 商店可能还要等等。

详情见： https://github.com/gantrol/Bing-Chat-Saver/issues/31

过几天会关闭这个 issue
