### ISSUE TITLE
保存记录的按钮消失了

### ISSUE THREAD

**Issue by jklw4** [gantrol/Bing-Chat-Saver#34]
刚发现突然没有了保存记录的按钮了，但是插件还是在工作，可以隐藏欢迎和反馈界面，但是没有保存记录的按钮了

**Comment by jklw4** [comment]
抱歉，是可以隐藏欢迎界面，但是不能隐藏反馈界面

**Comment by gantrol** [comment]
这个已修复，5 月 4 号的更新影响到了。release 发布了，chrome 商店可能还要等等。

详情见： https://github.com/gantrol/Bing-Chat-Saver/issues/31
