### ISSUE TITLE
可以导出被屏蔽的内容吗？

### ISSUE THREAD

**Issue by z14git** [gantrol/Bing-Chat-Saver#35]
有时候，Bing 在回答了问题后，会突然撤消回答，并将回答改为 "Sorry! That’s on me, I can’t give a response to that right now. What else can I help you with?"。

作者有办法获取被撤消的回答吗？如果能屏蔽掉这个撤消功能就更好了。

**Comment by gantrol** [comment]
这个是内容审查没过，一个月前应该是可以前端屏蔽的，不过最近我没用必应聊天了，不太了解这方面的变化
